### ISSUE TITLE
trivial-ldap.lisp contains unsafe DECLAIM

### ISSUE THREAD

**Issue by luismbo** [rwiker/trivial-ldap#11]
`trivial-ldap.lisp` contains the following `declaim`:

```
(declaim (optimize (speed 3) (safety 1) (debug 1) (compilation-speed 0)))
```

According to the CLHS, the effects of such a declaration may persist after that file is compiled. In particular, that is the case in Allegro CL and it causes all subsequent compilation to occur with speed > safety, which can be disastrous. :-)

I'm inclined to suggest simply removing the declaration, but other options include (a) using [ASDF's facilities](https://common-lisp.net/project/asdf/asdf/Controlling-file-compilation.html) to restrict the declaim to specific files or (b) replacing `declaim` with `declare`s in specific hotspots.

**Comment by rwiker** [comment]
Removed the declaim; thanks!

**Comment by rwiker** [comment]
Ouch. I had no idea that this was not file-scope (or rest-of-file scope). I'll fix this immediately.
